[build]
  command = "npm run build"
  publish = "dist/portfolio/browser"

[functions]
  directory = "dist/portfolio/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200